version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ec2-user/webservice/

hooks:
  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: •/codedeploy/applicationStart.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 300
      runas: ubuntu
