name: Build artifact



on:

  push:

    branches: [main]

  workflow_dispatch:



jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: Create webservice Folder

        run: rsync -arv . ./webservice

      - name: Switch to webservice Folder

        run: |

          zip -r webservice.zip webservice

      - uses: actions/upload-artifact@v1

        with:

          name: webservice.zip

          path: ${{ github.workspace }}/webservice.zip



  build:

    runs-on: ubuntu-latest

    needs: test

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

        with:

         name: webservice.zip

      - name: Display structure of downloaded files
